# app-springboot-demo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
      annotations:
        # Подсказываем Prometheus (если используете автоскрап по аннотациям)
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: springboot-demo
          image: ghcr.io/grafana/micrometer-spring-demo:latest
          ports:
            - containerPort: 8080
          env:
            # включаем экспорт метрик в формате Prometheus
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
            - name: MANAGEMENT_SERVER_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-demo
  namespace: app
  labels:
    app: springboot-demo
spec:
  type: ClusterIP
  selector:
    app: springboot-demo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
